accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views 

app_name = "accounts"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name='signup'),
    path("signup_success/", views.SignUpSuccessView.as_view(), name='signup_success'),
    path("login/", auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path("logout/", auth_views.LogoutView.as_view(template_name='logout.html'), name='logout')
]

kouryaku/urls.py
from django.urls import path
from . import views


app_name = 'kouryaku'

urlpatterns=[
    path("", views.IndexView.as_view(),     name="index"),
    path('post/', views.CreateLineupView.as_view(), name='post'),
    path("post_done/", views.PostSuccessView.as_view(), name='post_done'),
    path("posts/Character/<int:Map>", views.MapView.as_view(), name='post_map'),
    path("posts/<int:Character>", views.CharacterView.as_view(), name='post_character'),
    path("user-list/<int:user>", views.UserView.as_view(), name='user_list'),
    path('post_detail/<int:pk>', views.DetailView.as_view(), name='post_detail'),
    path("mypage/", views.MypageView.as_view(), name='mypage'),
    path("post_detail/<int:pk>/delete/", views.PostDeleteView.as_view(), name='post_delete'),
    path('post_detail/<int:pk>/edit/', views.PostEditView.as_view(), name='post_edit'),
    path('post_detail/<int:pk>/comment/create/', views.CommentCreate.as_view(), name='comment_create'), 
    path('post_detail/<int:pk>/comment/edit/', views.CommentEditView.as_view(), name='comment_edit'),
    path("contact/", views.ContactView.as_view(), name='contact'
    ),
    path('post_detail/<int:pk>/comment/delete/', views.CommentDeleteView.as_view(), name='comment_delete'),


    
    ]

kouryakuproject/urls.py

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('kouryaku.urls')),
    path("", include('accounts.urls')),
      path("password_reset/", auth_views.PasswordResetView.as_view(template_name ="password_reset.html"),
         name = 'password_reset'),
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(template_name ="password_reset_sent.html"),
         name = 'password_reset_done'

    ),
    path("reset/<uidb64>/<token>", auth_views.PasswordResetConfirmView.as_view(template_name ="password_reset_form.html"),
         name = 'password_reset_confirm'

    ),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(template_name ="password_reset_done.html"),
         name = 'password_reset_complete'),
]
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)


base/models.py
from django.db import models

# Create your models here.

kouryaku/forms.py
from django.forms import ModelForm
from django import forms
from .models import Lineups
class LineupsForm(ModelForm):
    class Meta:
        model= Lineups
        fields= ['Character', 'Map', 'title', 'comment', 'image1', 'image2', 'image3']
from .models import Comments
 
 
class CommentCreateForm(ModelForm):
    """コメントフォーム"""
    class Meta:
        model = Comments
        # exclude = ('user',  'target', 'created_at')
        fields = ['text']
class ContactForm(forms.Form):
    # フォームのフィールドをクラス変数として定義
    name = forms.CharField(label ='お名前')
    email = forms.EmailField(label ='メールアドレス')
    title =  forms.CharField(label ='件名')
    message =  forms.CharField(label ='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        '''ContactFromのコンストラクター
        
            フィールドの初期化を行う
        '''
        super().__init__(*args, **kwargs)
        #nameフィールドのplaceolderにメッセージを登録
        self.fields['name'].widget.attrs['placeholder'] = \
            'お名前を入力してください'
        
        #nameフィールドを出力する<input>タグのclass属性を設定
        self.fields['name'].widget.attrs['class'] = 'form-control'

         #emailフィールドのplaceolderにメッセージを登録
        self.fields['email'].widget.attrs['placeholder'] = \
            'メールアドレスを入力してください'
        
        #emailフィールドを出力する<input>タグのclass属性を設定
        self.fields['email'].widget.attrs['class'] = 'form-control'

         #titleフィールドのplaceolderにメッセージを登録
        self.fields['title'].widget.attrs['placeholder'] = \
            'タイトルを入力してください'
        
        #titleフィールドを出力する<input>タグのclass属性を設定
        self.fields['title'].widget.attrs['class'] = 'form-control'

         #messageフィールドのplaceolderにメッセージを登録
        self.fields['message'].widget.attrs['placeholder'] = \
            'メッセージを入力してください'
        
        #messageフィールドを出力する<input>タグのclass属性を設定
        self.fields['message'].widget.attrs['class'] = 'form-control'
 
 

base/views.py
from django.shortcuts import render
from django.views.generic import base as BaseView

class BaseView():
    method_only = ['GET']
    def main(self):
        # セッションから遷移元リストを取得し、最後尾のパスをリダイレクト先に設定する
        back_redirect_histories = self.request.session['back_redirect_histories']
        self.redirect_to = back_redirect_histories[-1]
    # def view(cls, request, **kwargs):
       
    #     try:
    #         this.main()
    #     except ApplicationException as ae:
    #         # 業務例外発生時
    #         ...
    #         ..
    #         .
    #     else:
    #         cls.__update_back_redirect_histories(request) # request.META.HTTP_REFERERをセッションにつめる処理
    #     return this.response()

    def __update_back_redirect_histories(request):
        """ このメソッド追加
        """
        # 戻るボタン押下時は何もしない
        if 'back' in request.path:
            return

        # リファラ(遷移元)をセッションに保存する処理
        back_redirect_histories = list()
        if 'HTTP_REFERER' in request.META and request.META['HTTP_REFERER']:
            # 既に遷移元のリストがセッションに存在する場合はそのリストに追加する。
            if 'back_redirect_histories' in request.session:
                back_redirect_histories = request.session['back_redirect_histories']
            if len(back_redirect_histories) == 0 or back_redirect_histories[-1] != request.build_absolute_uri():
                back_redirect_histories.append(request.META['HTTP_REFERER'])

            # 遷移元リストを後方から走査し、現在のURLと一致するリファラが見つかった場合、
            # リファラの最後尾から見つかった位置までのリファラをリストから削除する。
            rm_index = 0
            for redirect in reversed(back_redirect_histories):
                rm_index += 1
                if redirect == request.build_absolute_uri():
                    rm_index = -rm_index # 正数を負数に変換
                    break;
            if rm_index < 0:
                back_redirect_histories = back_redirect_histories[:rm_index]

            # 新しい遷移元リストでセッションを更新
            request.session['back_redirect_histories'] = back_redirect_histories

kouryaku/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView,ListView
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import LineupsForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .models import Lineups
from django.views.generic import DetailView
from django.views.generic import DeleteView
from django.views.generic import UpdateView
from datetime import datetime, timezone
from .models import Comments
from .forms import CommentCreateForm
from django.shortcuts import redirect, get_object_or_404
from .forms import ContactForm
from django.contrib import messages
from django.core.mail import EmailMessage
from django.views.generic import FormView
from django.urls import reverse




class IndexView(ListView):
    template_name = "index.html"
    model = Lineups
    queryset = Lineups.objects.order_by('-posted_at')
    paginate_by= 9

class MapView(ListView):
    template_name = "index.html"
    model = Lineups

    paginate_by= 9
    def get_queryset(self):
        category_id=self.kwargs['Map']
        categories= Lineups.objects.filter(
            Map=category_id).order_by('posted_at')
        return categories

class CharacterView(ListView):
    template_name = "index.html"
    model = Lineups

    paginate_by= 9
    def get_queryset(self):
        category_id=self.kwargs['Character']
        categories= Lineups.objects.filter(
            Character=category_id).order_by('posted_at')
        return categories


class MapView(ListView):
    template_name = "index.html"

    paginate_by= 9
    def get_queryset(self):
        category_id=self.kwargs['Map']
        categories= Lineups.objects.filter(
            Map=category_id).order_by('posted_at')
        return categories

class UserView(ListView):
    template_name = "index.html"

    paginate_by= 9
    def get_queryset(self):
        user_id=self.kwargs['user']
        user_list= Lineups.objects.filter(
            user=user_id).order_by('posted_at')
        return user_list

class DetailView(DetailView):
    template_name= "detail.html"
    model = Lineups


    def get_context_data(self, **kwargs):
        post_pk = self.kwargs['pk']
        detail = get_object_or_404(Lineups, pk=post_pk)
        context = super().get_context_data(**kwargs)
        context.update({"detail":detail,
                        "comments":Comments.objects.filter(target=detail.id)
        })
        return context
class ContactView(FormView):
    # '''問い合わせページを表示するビュー
    
    # フォームで入力されたデータを取得し、メールの作成と返信を行う
    # '''
    #contct.htmlをレンダリングする
        template_name ='contact.html'
    
        #クラス変換form_classにform.pyで定義したContactFromを設定
        form_class = ContactForm
        #送信完了後にリダイレクトするページ
        success_url = reverse_lazy('kouryaku:index')

        # def get_context_data(self, **kwargs):
        #     context = super().get_context_data(**kwargs)
        #     print(context['form'])
        #     return context

        def form_valid(self, form):
    

            name =  form.cleaned_data['name']
            email =  form.cleaned_data['email']
            title =  form.cleaned_data['title']
            message =  form.cleaned_data['message']
        #     #メールのタイトルの書式を設定   
            subject =  'お問い合わせ: {}'.format(title)

        #     #フォームの入力データの書式を設定
            message = \
            '送信者名: {0}\nメールアドレス: {1}\n タイトル: {2}\n メッセージ:\n{3}' \
           .format(name, email, title , message)

            from_email = 'admin@example.com'

            to_list = ['halu.825.bakura@gmail.com']

        #     # Email Messageオブジェクトを生成
            message = EmailMessage(subject=subject, 
                                body=message,
                                from_email=from_email,
                                to=to_list,          
            )
        #     #EmailMessage   クラスのsend()でメールサーバからメールを送信
            message.send()
        #     #送信後に完了するメッセージ
            messages.success(
                self.request, 'お問い合わせは正常に送信されました。')
        #     # 戻り値はスーパークラスの form_valid()の戻り値(HttpResponseRedirect)
            return super().form_valid(form)

   
    
 
  





@method_decorator(login_required, name='dispatch')

class CreateLineupView(CreateView):
    form_class = LineupsForm
    template_name = "post_lineup.html"
    success_url = reverse_lazy('kouryaku:post_done')
    def form_valid(self, form):
        postdata= form.save(commit=False)
        postdata.user=self.request.user
        postdata.save()
        return super().form_valid(form)

class PostSuccessView(TemplateView):
    template_name = 'post_success.html'

class MypageView(ListView):
    template_name='mypage.html'
    paginate_by =9
    def get_queryset(self):
        queryset = Lineups.objects.filter(
            user=self.request.user).order_by('posted_at')
        return queryset

class PostDeleteView(DeleteView):
    model = Lineups
    template_name = 'post_delete.html'
    success_url = reverse_lazy('kouryaku:index')
    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)

class PostEditView(UpdateView):
    template_name = 'post_edit.html'
    
    model = Lineups
    
    fields = ('Character', 'Map', 'title', 'comment','image1', 'image2','image3')
    success_url = reverse_lazy('kouryaku:post_detail', )

    def form_valid(self, form):
            post_pk = self.kwargs['pk']
            postdata = form.save(commit=False)
            postdata.posted_at = datetime.now()
            postdata.save()
            # return super().form_valid(form)
            return redirect('kouryaku:post_detail', pk=post_pk)

class CommentCreate(CreateView):
    """コメント投稿ページのビュー"""
    template_name = 'comment_form.html'
    model = Comments
    form_class = CommentCreateForm


    
    def form_valid(self, form):

        post_pk = self.kwargs['pk']
        post = get_object_or_404(Lineups, pk=post_pk)
        comment = form.save(commit=False)
        comment.user=self.request.user
        comment.target = post
        comment.save()
        return redirect('kouryaku:post_detail', pk=post_pk)
 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['kouryaku'] = get_object_or_404(Lineups, pk=self.kwargs['pk'])
        return context
class CommentEditView(UpdateView):
        template_name = 'comment_edit.html'
        model = Comments
        
        success_url = reverse_lazy('kouryaku:index')
        fields= {'text'}

        

        
    
        def form_valid(self, form):
                
                postdata = form.save(commit=False)
                postdata.posted_at = datetime.now()
                postdata.save()
                return super().form_valid(form)
        # model = Comments
        # form_class = CommentCreateForm
        # def get_success_url(self):
        #     return reverse_lazy("post_detail", kwargs={"pk":self.kwargs["pk"]})


    
       

         
        # def form_valid(self, form):
        #     postdata = form.save(commit=False)
        #     postdata.posted_at = datetime.now()
        #     postdata.save()
        #     return super().form_valid(form) 
            # post_pk = self.kwargs['pk']
            # post =  get_object_or_404(Comments, pk=self.kwargs['pk'])
            # comment = form.save(commit=False)
            # comment.user=self.request.user
            # comment.id = post
            # comment.save()
            # return redirect('kouryaku:post_detail',  pk=post_pk)
class CommentDeleteView(DeleteView):
    model = Comments
    template_name = 'comment_delete.html'
    success_url = reverse_lazy('kouryaku:index')
    def delete(self, request, *args, **kwargs):
        return super().delete(request, *args, **kwargs)


kouryaku/templates/comment_delete.html
{% extends 'base.html' %}
{% block title %}Post Delete{% endblock %}
{% block contents %}
<br>
<div class="container">
    <div class="row">
        <div class="col offset-3">
                <form method="POST">
                    <br>
                    <p>削除してもいいですか？</p>
                    {% csrf_token %}
                    <button class="btn btn-bd-primary my-2" type="submit">削除</button>
                    
                     <a href="{{request.META.HTTP_REFERER}}">
                     <button type="button" class="btn btn-danger" >戻る</button>
            
        </div>
    </div>
</div>
{% endblock %}

kouryaku/templates/comment_edit.html
{% extends 'base.html' %}
{% block title %}Comment Edit{% endblock %}
        {% block contents %}
        <br>
        <div class="container">

            <div class="row">
                <div class="col offset-3">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button class="btn btn-primary my-2" type="submit">保存</button>
                        
                         <a href="{{request.META.HTTP_REFERER}}">
                            <button type="button" class="btn btn-danger" >戻る</button>
                    
                </div>
            </div>
        </div>
        {% endblock %}

kouryaku/templates/comment_form.html
{%  extends 'base.html' %}

{% block title %}commentcreate{% endblock %}
{% block contents %}
{% load widget_tweaks %}
<div class="container col-lg-6 offset-lg-3">
  <p class="titleline">{{ post.title }}</p>
  <form action="" method="POST" id="comment-form">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="field">
      {{ field.label_tag }}
      {% render_field field class="form-control" %}
 
      {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <div class="row my-3">
      <button type="submit" class="btn btn-primary">投稿する</button>

      <a href="{{request.META.HTTP_REFERER}}">
        <button type="button" class="btn btn-danger" >戻る</button>
      </a>
    </div>
  </form>
</div>
{% endblock %}

kouryaku/templates/contact.html
<!--<!DOCTYPE html>と <html lang ="ja"を削除-->
<!-- ベーステンプレートを適用する-->
{% extends 'base.html' %}
<!--静的ファイルのURLを生成するstaticをダウンロードする-->
{% load static %}   
<!--ヘッダー情報のページタイトルは
    ベーステンプレートを利用するページで設定する-->
{% block title %}Contact{% endblock %}
       
        <!-- Navigation-->
      
        <!-- Page Header-->
        {% block header %}
        <header >
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="page-heading">
                            <h1>Contact Me</h1>
                            <span class="subheading">Have questions? I have answers.</span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        <!-- Main Content-->
        {% block contents %}
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <strong>連絡を取りたいですか？
                            以下のフォームに記入してメッセージを送信してください
                            できるだけ早くご連絡します</strong>
                            <!--フォームの送信が成功したときのメッセージを表示するためのコード-->
                            <!--requestにmessageオブジェクトが存在している場合-->
                            {% if messages %}
                            <!--箇条書きのスタイルを無効にした<ul>タグでメッセージを出力-->
                            <ul class="list-unstyled" style="list-style: none;">    
                                <!-- forでmessagesを取り出す-->
                                {% for message in messages %}
                            <!-- message.tagsが存在する場合はclass属性にCSSのクラスを設定-->
                                <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                                <!-- messageに格納されているメッセージを出力-->
                                    {{ message }}
                                </li>
                                {% endfor %}

                            
                            </ul>
                        {% endif %} 
                            <!--　以下フォームを表示するためのコード-->
                        <div class="my-5">
                            <!-- method="post"を追加-->
                            <form method="post">
                                <!-- CSRF対策のテンプレートタグ-->
                                {% csrf_token %}
                                <!-- formで定義されているフィールドの値を取り出す-->
                                {% for field in form %}
                                <div class="form-floating">
                                    <div class="form-group floating-label-form-group controls">
                                        <!-- <label>タグを作成-->
                                            {{ field.label_tag }}
                                            <!--　フィールドの設定値を<input>タグで出力-->
                                            {{ field }}
                                            <!-- pを追加-->
                                            <p class="help-block text-danger"></p>

                                    </div>
                                </div>
                                {% endfor %}
                                <br>
                                <!-- 送信用のボタン-->
                                <button type = "submit"
                                            class="btn btn-primary"
                                            id ="sendMessageButton">送る</button>

                            </form>

                           
                        </div>
                    </div>
                </div>
            </div>

            <hr>
        </main>
        {% endblock %}

kouryaku/templates/detail.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}post detail {% endblock %}
{% block contents %}
<br>
<div class="detail">



<h1 class="text-white">{{object.title}}</h1>
<h3>{{object.comment}}</h3>
<br>


<p><img src="{{ object.image1.url }}" width="75%"></img></p>
</div>
{% if object.image2 %}
<p><img src="{{ object.image2.url }}"></img></p>
{% endif %}
{% if object.image3 %}
<p><img src="{{ object.image3.url }}"></img></p>
{% endif %}

{% if request.user == object.user %}
<form method="POST">
<a href="{% url 'kouryaku:post_edit' object.pk %}"
class="btn btn-primary my-2">編集する</a>
{% endif %}
{% if request.user == object.user %}
<form method="GET">
    {% csrf_token %}
    <a href="{% url 'kouryaku:post_delete' object.pk %}"
    class="btn btn-primary my-2">削除する</a>
    {% endif %}

    </div>
    {% if user.is_authenticated %}
    <type="text" id="detail_id" name="detail_id" value="{{ object.id }}">
    <a class="btn btn-success col-3 offset-2" href="{% url 'kouryaku:comment_create' object.id %}">コメントを投稿する</a>
</form>
</div>
{% else %}
<type="text" id="detail_id" name="detail_id" value="{{ object.id }}">
<a class="btn btn-success col-3 offset-2" href="{% url 'accounts:login' %}">コメントを投稿する</a>
</form>
</div>
{% endif %}
<div class="commentform">


    {% for comment in comments %}
        <div class="border-bottom">{{comment.user}}

        {{comment.posted_at}}
        </div>
        <div class='mt-2'>{{comment.text}}</div>
        {% if request.user == comment.user %}
        <a class="commentedit" href="{% url 'kouryaku:comment_edit' comment.pk %}">編集する</a>>
        <a class="comment_delete" href="{% url 'kouryaku:comment_delete' comment.pk %}">削除する</a>>
        {% endif %}

        </div>
    </div>
    {% endfor %}
 
{% endblock %}

kouryaku/templates/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block contents %}

{% include "post_title.html" %}

{% include "post_list.html" %}

{% include "pagination.html" %}
{% endblock %}

kouryaku/templates/mypage.html
{% extends 'base.html' %}
{% block title %}My page{% endblock %}
{% block contents %}
{% if user.is_authenticated %}
    <br>
    <div style="text-align: center;">
    <h4>{{user.username}}さんのマイページ</h4>
    {% if object_list.count == 0 %}
    <p>{{user.username}}さんの投稿はありません。</p>
    {% else %}
    <p>投稿<strong>{{object_list.count}}</strong>件</p>
    {% endif %}
    <a href="{% url 'kouryaku:post' %}">投稿する</a>
</div>
    <hr>
    {% endif %}
{% include "post_list.html" %}
{% include 'pagination.html' %}
{% endblock %}

kouryaku/templates/pagination.html
<!-- ページネーションのアイコンを左右中央に配置-->
<ul class="pagination"
    style="justify-content:center">
<!--
    前ページを表示するアイコンとリンクの設定
    ページネーションされたPageオブジェクトをpage_objで取得
    Page.has_previous:　直前にページがある場合はTrueを返す
-->
{% if page_obj.has_previous %}

<!--
    前のページが存在する場合はそのページへのリンクが設定されたアイコン{<<}を表示
    Page.previous_page_number:直前のページ番号を返す
-->
<li class="page-item">
    <a class="page-link"
        href="?page={{page_obj.previous_page_number}}"
        aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
    </a>
</li>
{% endif %}
<!--
    全てのページについてページ番号のアイコンを表示
    pafinator.page_range: [1, 2, 3, 4] のように1から始まるページ番号を返す
    page_obj.paginator.page_rangeとして取得
    ブロックパラメーターnumに順次取り出される
-->
{% for num in page_obj.paginator.page_range %}
<!--
    書くページのアイコンを出力
    Page.number: 引き渡されたページのページ番号を返す
-->
{% if page_obj.number == num %}
<!--
    処理中のページ番号が引き渡されたページのページ番号と一致する場合は
    ページ番号のアイコン(アクティブ状態)を表示(リンクは設定しない)
-->
<li class="page-item active">
    <span class="page-link">{{ num }}</span>
    </li>
    <!--
        ページ番号が引き渡されたページのページ番号と一致しない場合
    -->
    {% else %}
    <!--
        ページ番号のアイコン(アクティブ状態ではない)にリンクを設定して表示
    -->
    <li class="page-item">
        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
    </li>
    {% endif %}

{% endfor %}
<!--
    次ページへのリンクを示すアイコンの表示
    Page.has_next:　次のページがある場合にTrueを返す
-->
{% if page_obj.has_next %}
<!--
    次ページが存在する場合はリンクを設定したアイコン[>>]を表示
    Page.next_page_number: 次のページ番号を返す
-->
<li class="page-item">
    <a class="page-link"
    href="?page={{ page_obj.next_page_number }}"
    aria-label="Next">
    <span aria-hidden="true">&raquo;</span>
</a>
</li>
{% endif %}
</ul>

kouryaku/templates/post_delete.html
{% extends 'base.html' %}
{% block title %}Post Delete{% endblock %}
{% block contents %}
<br>
<div class="container">
    <div class="row">
        <div class="col offset-3">
                <form method="POST">
                    <br>
                    <p>削除してもいいですか？</p>
                    {% csrf_token %}
                    <button class="btn btn-bd-primary my-2" type="submit">削除</button>
                    <a href="{% url 'kouryaku:post_detail' object.pk %}"
                    class="btn btn-danger">キャンセル</a>
            
        </div>
    </div>
</div>
{% endblock %}

kouryaku/templates/post_list.html

<div class="album py-5 bg-body-tertiary">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
       {% for record in object_list %}
        <div class="co">
          <div class="card shadow-sm">
          <img src="{{ record.image1.url }}"
            class="bd-placeholder-img card-img-top"
            width="100%" height="225"
            xmlns="http://www.w3.org/2000/svg"
            role="img" aria-label="Placeholder: Thumbnail"
            preserveAspecRatio="xMidYMid slice"
            focusable="false">
            <title>Plaseholder</title>
            <rect width="100%" height="100%" fill="#55595c"/>
          </img>
         
           
         
          <div class="card-body">
              <p class="card-text">{{record.title}}</p> 
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary"
                  onclick="location.href='{% url 'kouryaku:post_detail' record.pk %}'">
                  閲覧</button>
                  <button type="button"
                  class=" btn btn-sm btn-outline-secondary"
                  onclick="location.href='{% url 'kouryaku:post_character'   Character=record.Character.id %}'">
                  {{record.Character.title}}
                  </button>
                  <button type="button"
                  class=" btn btn-sm btn-outline-secondary"
                  onclick="location.href='{% url 'kouryaku:post_map'   Map=record.Map.id %}'">
                  {{record.Map.title}}
                  </button>

                <a href="{% url 'kouryaku:user_list' user=record.user.id %}">
                <small class="text-muted">{{record.user.username}}</small>
                 
              </a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
   

kouryaku/templates/post_success.html
{% extends 'base.html' %}
{% block title %}Post Success{% endblock %}
{% block contents %}
<br><br>
<h4>投稿が完了しました</h4>
{% endblock %}

kouryaku/templates/post_title.html
<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">定点投稿サイト</h1>
        <p class="lead text-warning">
          自分だけしか知らないであろう定点を共有しあいましょう！
          素敵な定点とコメントをお待ちしています！
        </p>
        <p>
          {% if user.is_authenticated %}
          <a href="{% url 'kouryaku:post' %}"
            class="btn btn-primary my-2">投稿する</a>
            <a href="{% url 'accounts:logout' %}"
              class="btn btn-primary my-2">ログアウト</a>
              {% else %}
          <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">今すぐサインアップ</a>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary my-2">登録済みの方はログイン</a>
          {% endif %}
        </p>
      </div>
    </div>
  </section>