accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views 

app_name = "accounts"
urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name='signup'),
    path("signup_success/", views.SignUpSuccessView.as_view(), name='signup_success'),
    path("login/", auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path("logout/", auth_views.LogoutView.as_view(template_name='logout.html'), name='logout')
]

kouryaku/urls.py
from django.urls import path
from . import views


app_name = 'kouryaku'

urlpatterns=[
    path("", views.IndexView.as_view(),     name="index"),
    path('post/', views.CreateLineupView.as_view(), name='post'),
    path("post_done/", views.PostSuccessView.as_view(), name='post_done'),
    path("posts/Character/<int:Map>", views.MapView.as_view(), name='post_map'),
    path("posts/<int:Character>", views.CharacterView.as_view(), name='post_character'),
    path("user-list/<int:user>", views.UserView.as_view(), name='user_list'),
    path('post_detail/<int:pk>', views.DetailView.as_view(), name='post_detail'),
    path("mypage/", views.MypageView.as_view(), name='mypage'),
    path("post_detail/<int:pk>/delete/", views.PostDeleteView.as_view(), name='post_delete'),
    path('post_detail/<int:pk>/edit/', views.PostEditView.as_view(), name='post_edit'),
    path('post_detail/<int:pk>/comment/create/', views.CommentCreate.as_view(), name='comment_create'), 
    path('post_detail/<int:pk>/comment/edit/', views.CommentEditView.as_view(), name='comment_edit'),
    path("contact/", views.ContactView.as_view(), name='contact'
    ),
    path('post_detail/<int:pk>/comment/delete/', views.CommentDeleteView.as_view(), name='comment_delete'),


    
    ]

kouryakuproject/urls.py

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('kouryaku.urls')),
    path("", include('accounts.urls')),
      path("password_reset/", auth_views.PasswordResetView.as_view(template_name ="password_reset.html"),
         name = 'password_reset'),
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(template_name ="password_reset_sent.html"),
         name = 'password_reset_done'

    ),
    path("reset/<uidb64>/<token>", auth_views.PasswordResetConfirmView.as_view(template_name ="password_reset_form.html"),
         name = 'password_reset_confirm'

    ),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(template_name ="password_reset_done.html"),
         name = 'password_reset_complete'),
]
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)


accounts/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView, CreateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name ="signup.html"
    success_url = reverse_lazy('accounts:signup_success')
    def form_valid(self, form):
        user = form.save()
        self.object = user
        return super().form_valid(form)
class SignUpSuccessView(TemplateView):
    template_name= "signup_success.html"


accounts/templates/login.html
{% load static %}
<!doctype html>
<html lang="ja">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Log in</title>

    <link rel="icon" type="image/x-icon" href={% static 'assets/favicon.ico' %} />

    

    

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href={% static "css/signin.css" %} rel="stylesheet">
  </head>
  <body class="text-center">
    <main class="form-signin">
      {% if form.errors %}
      <p style="color: red">ユーザー名とパスワードが一致しません。</p>
      {% endif %}
      <form method="post">
        {% csrf_token %}
        <img class="mb-4"
        src={% static "img/bootstrap-logo.svg" %}
        alt="" width="72"
        height="57">
        <h1 class="h3 mb-3 fw-normal">Plase sign in</h1>
        <label for="Username" class="visually-hidden">
          User name</label>
          <input type="text"
          name="username"
          id="id_username"
          maxlength="150"
          autocapitalize="none"
          autocomplete="username"
          class="form-control"
          placeholder="ユーザー名"
          required autofocus>
          <label for="Password" class="visually-hidden">
            Password</label>
            <input type="password"
            name="password"
            id="id_password"
            autocomplete="current-password"
            class="form-control"
            placeholder="パスワード"
            required autofocus>
            <input class="w-100 btn btn-lg btn-primary"
            type="submit"
            value="ログイン">
            <br><br>
            <p><a href="{% url 'accounts:signup' %}">サインアップしていない方はこちら</a></p>
            <p><a href="{% url 'password_reset' %}">パスワードを忘れましたか？</a></p>
            <input type="hidden"
              name="next"
              value="{% url 'kouryaku:index' %}">
      </form>
    </main>
  </body>
  
</html>

accounts/templates/logout.html
{% extends 'base.html' %}
{% block title %}Log out{% endblock %}
{% block contents %}
<h3>ログアウトしました</h3>
<p><a href="{% url 'kouryaku:index' %}">トップページへ</a></p>
    {% endblock %}

accounts/templates/password_reset.html
{% extends 'base.html' %}
{% block title %}Reset password{% endblock %}
{% block contents %}
<hr>
<h3>パスワードをリセットしますか？</h3>
<p>
    登録済みのメールアドレスを入力してください。
    パスワードリセットのリンクを記載したメールをすぐにお届けします。
</p>
<br>
<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="メールを受け取る" /><br>
</form>
<br>
<a href="{% url 'kouryaku:index'}"></a>
<hr>
{% endblock %}

accounts/templates/password_reset_done.html
<!DOCTYPE html>
<html lang="ja">
    <head>

    </head>
    <body>
        <h2>パスワードがリセットされました</h2>
        
        <br>
        <a href="{% url 'accounts:login' %}">ログインはこちら</a>
        <a href="{% url 'kouryaku:index' %}">トップページへ</a>
    </body>
</html>

accounts/templates/password_reset_form.html
<!DOCTYPE html>
<html lang="ja">
    <head>

    </head>
    <body>
        <h4>
            新しいパスワードを2回入力してください。これにより、
            正しく入力できたことが確認できます。
        </h4>
        <br />
        <form action=""  method="POST">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="パスワードリセット"/>   
        </form>
    </body>
</html>

accounts/templates/password_reset_sent.html
{% extends 'base.html' %}
{% block title %}Send password reset{% endblock %}
{% block contents %}
<hr>
<h5>パスワードのリセット手順をメールで送信しました。
    メールはすぐに届きます。</h5>
    <br>
    <h6>
        メールが届かない場合は、登録済みのメールアドレスであるかどうかを確認し、迷惑メールフォルダーも確認してみてください。</h6>
        <br>
        <a href="{% url 'kouryaku:index' %}"></a>
        {% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% block title %}Sign up{% endblock %}
{% block contents %}
<div class="container">
    <div class="row">
        <div class="col offset-2">
<h3>サインアップ</h3>
<form method="post">
{% csrf_token %}

{% for field in form %}
<p>

    {{ field.label_tag }}<br>
    {{ field }}
    {% if field.help_text %}
    <small style="color:grey;">{{ field.help_text }}</small>
    {% endif %}
    {% for error in field.errors %}
    <p style="color: red;">{{ error }}</p>
    {% endfor %}
</p>
{% endfor %}
<p style="color: red;">
※メールアドレスはパスワードをリセットする際に必要となりますので、
登録をお願いします
</p>
<input type="submit" value="サインアップ">
</form>
<br>
<p><a href="{% url 'kouryaku:index' %}">
    登録をやめてトップページに戻る
</a></p>
</div>
</div>
</div>

{% endblock %}


accounts/templates/signup_success.html
{% extends 'base.html' %}
{% block tiele %}Registration Complate{% endblock %}
{% block contents %}
<h3>登録が完了しました</h3>
<p><a href="{% url 'accounts:login' %}">ログインはこちら</a></p>
{% endblock %}